### ISSUE TITLE
Could not load file or assembly IronPython

### ISSUE THREAD

**Issue by algady** [bluephoton/najm#4]
Hi, I'm getting this error while trying to run this app, I'm using VS2019
I tried to install older version of IronPython via NuGet package manager but no luck

**Comment by bluephoton** [comment]
@algady can you try to copy the python samples to the bin folder and see if this helps? So, you copy:

   From:   najm\Handlers\IPython\IPython\Samples
   To:        najm\Application\bin\Handlers\IPythonSamples

you'll need to create **Handlers\IPythonSamples** under the bin and copy folders there. You should end up with something like this:

![image](https://user-images.githubusercontent.com/3039102/104833472-b5c14380-584d-11eb-8c8d-3aa42d66bd66.png)

I assume you adjusted the config file to point to the right location to reach this point, let me know if this help...

**Comment by algady** [comment]
Hi and thanks for your reply, I'm not sure which config file to edit! 
What solution platform to select? (Any cpu/x64/x86)
Thanks

**Comment by algady** [comment]
![Microsoft  NET Framework 17_01_2021 22_13_48](https://user-images.githubusercontent.com/27924113/104858011-3c405880-5914-11eb-83aa-32cda19ed978.png)

**Comment by bluephoton** [comment]
The config file I was talking about is "\najm\Application\Najm.config"
Contents of this file is suitable for installed app. To run from VS, I had to set the Loaction attribute to empty string. Example:

```xml
<Handler Id="37581060-646F-49aa-8D1E-1E255B81B471" Location="" 
                Assembly="Najm.Handler.Default.dll" Param="" IsEnabled="true"/>
```

Then I copied the files as indicated earlier and the app started as expected.

Can you share some details on how you get this error?

**Comment by bluephoton** [comment]
Also make sure to check the references for the IPython handler project and make sure no errors there. Restoring nuget package for this project should solve any errors.

**Comment by algady** [comment]
First, this is how my Najm.config looks now and I get the same error!

```
`<?xml version="1.0"?>
<Najm>
  <Handlers>
    <!-- individual ids must match IDs you assign for your handler -->
    <Handler Id="37581060-646F-49aa-8D1E-1E255B81B471" Location="" Assembly="Najm.Handler.Default.dll" Param="" IsEnabled="true"/>
    <Handler Id="18E85847-29C2-4cb1-BDA5-0C971BFAB906" Location="" Assembly="Najm.Handler.Imaging.dll" Param="" IsEnabled="true"/>
    <Handler Id="1E93F6DB-F2D2-4bda-A114-2B6F633859AC" Location="" Assembly="Najm.Handler.Tables.dll" Param="" IsEnabled="true"/>
    <Handler Id="B705A42E-7671-4097-A366-6DC6534CCFF9" Location="" Assembly="Najm.Handler.IPython.dll" Param="" IsEnabled="true"/>
    <Handler Id="5CB3C60C-CB36-4925-9C00-69771586F5B9" Location="" Assembly="Najm.Handler.IPython.dll" Param="" IsEnabled="true"/>
    <Handler Id="871E9132-A1FF-410b-A897-5C72F003F7A4" Location="" Assembly="Najm.Handler.IPython.dll" Param="" IsEnabled="true"/>
  </Handlers>
</Najm>
```
`
Second, for references, I found errors on SetupDriver, all of them looks missing!
 I just downloaded the the project and run it with VS2019. I tried to install different versions of IronPython using NuGet package but no luck!
Can you please just zip the whole working project and upload it for me? this may help, thanks

**Comment by bluephoton** [comment]
I just cloned the repo when I saw your message, so I have same code you have. Only changes I made are:
- Restoring nuget package for iron python
- Updated config file- **yours is missing parameters for python handlers**
- Copies sample folders as indicated earlier 

we need to understand root cause of the error you getting, this will help others as well if they encountered similar issues.

as for setup, I’m not sure if it will work now...we can look at it later, but anyway it’s not related to the issue you have

**Comment by algady** [comment]
I edited it again and it looks like:

><Handler Id="37581060-646F-49aa-8D1E-1E255B81B471" Location="" Assembly="Najm.Handler.Default.dll" Param="" IsEnabled="true"/>
    <Handler Id="18E85847-29C2-4cb1-BDA5-0C971BFAB906" Location="" Assembly="Najm.Handler.Imaging.dll" Param="" IsEnabled="true"/>
    <Handler Id="1E93F6DB-F2D2-4bda-A114-2B6F633859AC" Location="" Assembly="Najm.Handler.Tables.dll" Param="" IsEnabled="true"/>
    <Handler Id="B705A42E-7671-4097-A366-6DC6534CCFF9" Location="" Assembly="Najm.Handler.IPython.dll" Param="..\Handlers\IPythonSamples\Console\Console.py" IsEnabled="true"/>
    <Handler Id="5CB3C60C-CB36-4925-9C00-69771586F5B9" Location="" Assembly="Najm.Handler.IPython.dll" Param="..\Handlers\IPythonSamples\TableFields\TableFields.py" IsEnabled="true"/>
    <Handler Id="871E9132-A1FF-410b-A897-5C72F003F7A4" Location="" Assembly="Najm.Handler.IPython.dll" Param="..\Handlers\IPythonSamples\Cube2GIF\cube2gif.py" IsEnabled="true"/>
  
still the same error!

**Comment by bluephoton** [comment]
What are the steps that resulted in this error? do you get this when app launch? or the app launch fine and you get it when starting a handler?

**Comment by algady** [comment]
when I run the app (press start in VS) just before the UI appears error message shows!

**Comment by bluephoton** [comment]
And how are the references look like in the IronPython project, do you see this:

![image](https://user-images.githubusercontent.com/3039102/104866323-25d5d500-58f3-11eb-88e3-7d9df4e72c8c.png)

**Comment by algady** [comment]
OK, now it works!
I changed (solution platform) from x64 to Any CPU and that solved the problem!
Thanks so much for your support.

**Comment by bluephoton** [comment]
You are welcome! Glad you figured it out, feel free to open other issues if you have more questions.
